// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJYmJLG7U7mu8_3T6Zqox8p15W4nPnWKY',
    appId: '1:194379848713:web:775c703ce1813254172cd8',
    messagingSenderId: '194379848713',
    projectId: 'moto-rental-app',
    authDomain: 'moto-rental-app.firebaseapp.com',
    storageBucket: 'moto-rental-app.appspot.com',
    measurementId: 'G-W6X4L410QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNIijsDZZJOKHNzgSy4yrXsuPzY2j3Do0',
    appId: '1:194379848713:android:27c1285b0f502a41172cd8',
    messagingSenderId: '194379848713',
    projectId: 'moto-rental-app',
    storageBucket: 'moto-rental-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvVq5L9rPT9Z5XCAHpRDHSWhyi67ZNROc',
    appId: '1:194379848713:ios:159d872d426bfc3c172cd8',
    messagingSenderId: '194379848713',
    projectId: 'moto-rental-app',
    storageBucket: 'moto-rental-app.appspot.com',
    iosClientId: '194379848713-00v8ijf8th1s3cfliek9219hd2839bm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvVq5L9rPT9Z5XCAHpRDHSWhyi67ZNROc',
    appId: '1:194379848713:ios:159d872d426bfc3c172cd8',
    messagingSenderId: '194379848713',
    projectId: 'moto-rental-app',
    storageBucket: 'moto-rental-app.appspot.com',
    iosClientId: '194379848713-00v8ijf8th1s3cfliek9219hd2839bm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrentalApp',
  );
}
